#!/bin/bash

HOOKS_DIR="${PWD}"/.git/hooks
RESULT=0

"${HOOKS_DIR}"/scripts/ant.sh; RESULT=$((${RESULT} + $?))
"${HOOKS_DIR}"/scripts/composer.sh pre-push; RESULT=$((${RESULT} + $?))
"${HOOKS_DIR}"/scripts/npm.sh pre-push; RESULT=$((${RESULT} + $?))

exit ${RESULT}
