theme = "modern"
icons = "awesome"

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
device = "BAT1"

[[block]]
block = "time"
interval = 60
format = "%Y-%m-%d %R"
